# Softmax, part 1

Task: practice using the `softmax` function.

**Why**: The softmax is a building block that is used throughout machine learning, statistics, data modeling, and even statistical physics. This activity is designed to get comfortable with how it works at a high and low level.

**Note**: Although "softmax" is the conventional name in machine learning, you may also see it called "soft *arg* max". The [Wikipedia article](https://en.wikipedia.org/w/index.php?title=Softmax_function&oldid=1065998663) has a good explanation.

## Setup

In [1]:
import torch
from torch import tensor
import ipywidgets as widgets
import matplotlib.pyplot as plt
%matplotlib inline

## Task

The following function defines `softmax` by using PyTorch built-in functionality.

In [2]:
def softmax_torch(x):
    '''Compute the softmax along the last axis, using PyTorch'''
    # axis=-1 means the last axis
    # This won't matter in this exercise, but it will matter when we get to batches of data.
    return torch.softmax(x, axis=-1)

Let's try the PyTorch softmax on an example tensor.

In [4]:
x = tensor([1., 2., 3.])
softmax_torch(x)

tensor([0.0900, 0.2447, 0.6652])

2. Fill in the following function to implement softmax yourself:

In [5]:
def softmax(xx):
    # Exponentiate x so all numbers are positive.
    expos = xx.exp()
    assert expos.min() >= 0
    # Normalize (divide by the sum).
    return expos / sum(expos)

3. Evaluate `softmax(x)` and verify (visually) that it is close to the `softmax_torch(x)` you evaluated above.

In [6]:
softmax(x)

tensor([0.0900, 0.2447, 0.6652])

4. Evaluate each of the following expressions (to make sure you understand what the input is), then evaluate `softmax_torch(__)` for each of the following expressions. Observe how each output relates to `softmax_torch(x)`. (Is it the same? Is it different? Why?)

- `x + 1`
- `x - 100`
- `x - x.max()`
- `x * 0.5`
- `x * 3.0`

In [12]:
x + 1

tensor([2., 3., 4.])

In [16]:
softmax_torch(x * 3.0)

tensor([0.0024, 0.0473, 0.9503])

*Same or different as `softmax_torch(x)`? Why?*

(repeat for the other expressions)

>For the first 3 operations, the `softmax_torch` operation was the same. The last two were different because we're adding a scale to each of the exponents. The difference is due to the behavior of exponents. Adding to an exponent in a softmax equation will make the exponent of the constant 'cancel out'. However, the multiplication (or division) will cause change.

## Analysis

1. A valid probability distribution has no negative numbers and sums to 1. Is `softmax(x)` a valid probability distribution? Why or why not?

>The `softmax` method is a valid distribution. The formula involves us dividing from a 'whole' (i.e. `sum(exp(x))`). It's only reasonable that sum of all the `probs` would equate to **1**.

Consider the following situation:

In [17]:
y2 = tensor([1., 0.,])
y3 = y2 - 1
y3

tensor([ 0., -1.])

In [18]:
y4 = y2 * 2
y4

tensor([2., 0.])

1. Are `softmax(y2)` and `softmax(y3)` the same or different? How could you tell without having to evaluate them?


>Both functions will return the same result. We aren't scaling (i.e. multiplying).

2. Are `softmax(y2)` and `softmax(y4)` the same or different? How could you tell without having to evaluate them?


>Both functions will return different results, due to multiplication of a `scale`.

## Optional Extension: Numerical Issues

### Task for Numerical Issues

5. *Numerical issues*. Assign `x2 = 50 * x`. Try `softmax(x2)` and observe that the result includes the dreaded `nan` -- "not a number". Something went wrong. **Evaluate the first mathematical operation in `softmax`** for this particularly problematic input. You should see another kind of abnormal value.

In [ ]:
x2 = 50 * x
softmax(x2)

tensor([0., nan, nan])

In [ ]:
# your code here (the first mathematical operation in `softmax`)

tensor([5.1847e+21,        inf,        inf])

6. *Fixing numerical issues*. Now try `softmax(x2 - 150.0)`. Observe that you now get valid numbers. Also observe how the constant we subtracted relates to the value of `x2`.

In [ ]:
# your code here

tensor([3.7835e-44, 1.9287e-22, 1.0000e+00])

7. Copy your `softmax` implementation to a new function, `softmax_stable`, and change it so that it subtracts `xx.max()` from `xx` before exponentiating. (Don't use any in-place operations; just use `xx - xx.max()`) Verify that `softmax_stable(x2)` now works, and obtains the same result as `softmax_torch(x2)`

In [ ]:
# your code here

tensor([3.7835e-44, 1.9287e-22, 1.0000e+00])

In [ ]:
softmax_torch(x2)

tensor([3.7835e-44, 1.9287e-22, 1.0000e+00])

### Analysis of Numerical Issues

3. Explain why `softmax(x2)` failed.

*your answer here*

4. Use your observations in \#1-2 above to explain why `softmax_stable` still gives the correct answer for `x` even though we changed the input.

*your answer here*

5. Explain why `softmax_stable` doesn't give us infinity or Not A Number anymore for `x2`.

*your answer here*

## Extension *optional*

Try to prove your observation in Analysis \#1 by symbolically simplifying the expression `softmax(logits + c)` and seeing if you can get `softmax(logits)`. Remember that `softmax(x) = exp(x) / exp(x).sum()` and `exp(a + b) = exp(a)exp(b)`.